/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Property from './Property';





/**
* The AnswerResource model module.
* @module model/AnswerResource
* @version 3.0.7
*/
export default class AnswerResource {
    /**
    * Constructs a new <code>AnswerResource</code>.
    * @alias module:model/AnswerResource
    * @class
    * @param answer {module:model/Property} The answer to the question. Different 'type' values indicate different structures as the answer may be test, image, etc. See information on additional properties for the list and their structures
    * @param correct {Boolean} Whether the answer is correct or not
    */

    constructor(answer, correct) {
        

        
        

        this['answer'] = answer;this['correct'] = correct;

        
    }

    /**
    * Constructs a <code>AnswerResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AnswerResource} obj Optional instance to populate.
    * @return {module:model/AnswerResource} The populated <code>AnswerResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnswerResource();

            
            
            

            if (data.hasOwnProperty('answer')) {
                obj['answer'] = Property.constructFromObject(data['answer']);
            }
            if (data.hasOwnProperty('correct')) {
                obj['correct'] = ApiClient.convertToType(data['correct'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
    * The answer to the question. Different 'type' values indicate different structures as the answer may be test, image, etc. See information on additional properties for the list and their structures
    * @member {module:model/Property} answer
    */
    answer = undefined;
    /**
    * Whether the answer is correct or not
    * @member {Boolean} correct
    */
    correct = undefined;
    /**
    * The unique ID for that resource
    * @member {String} id
    */
    id = undefined;








}


