/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Behavior model module.
* @module model/Behavior
* @version 3.0.7
*/
export default class Behavior {
    /**
    * Constructs a new <code>Behavior</code>.
    * @alias module:model/Behavior
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Behavior</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Behavior} obj Optional instance to populate.
    * @return {module:model/Behavior} The populated <code>Behavior</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Behavior();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type_hint')) {
                obj['type_hint'] = ApiClient.convertToType(data['type_hint'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * Used for polymorphic type recognition and thus must match an expected type with additional properties
    * @member {String} type_hint
    */
    type_hint = undefined;








}


