/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import LeaderboardEntryResource from './LeaderboardEntryResource';





/**
* The LeaderboardResource model module.
* @module model/LeaderboardResource
* @version 3.0.7
*/
export default class LeaderboardResource {
    /**
    * Constructs a new <code>LeaderboardResource</code>.
    * @alias module:model/LeaderboardResource
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>LeaderboardResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LeaderboardResource} obj Optional instance to populate.
    * @return {module:model/LeaderboardResource} The populated <code>LeaderboardResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeaderboardResource();

            
            
            

            if (data.hasOwnProperty('entries')) {
                obj['entries'] = ApiClient.convertToType(data['entries'], [LeaderboardEntryResource]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('strategy')) {
                obj['strategy'] = ApiClient.convertToType(data['strategy'], 'String');
            }
        }
        return obj;
    }

    /**
    * The paginated list of user results, in order from best to worst
    * @member {Array.<module:model/LeaderboardEntryResource>} entries
    */
    entries = undefined;
    /**
    * The id of the leaderboard
    * @member {Number} id
    */
    id = undefined;
    /**
    * The name of the strategy that defines how entries are stored and compared
    * @member {String} strategy
    */
    strategy = undefined;








}


