/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PasswordResetRequest model module.
* @module model/PasswordResetRequest
* @version 3.0.7
*/
export default class PasswordResetRequest {
    /**
    * Constructs a new <code>PasswordResetRequest</code>.
    * A request to reset a user&#39;s password by using a known user property
    * @alias module:model/PasswordResetRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PasswordResetRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PasswordResetRequest} obj Optional instance to populate.
    * @return {module:model/PasswordResetRequest} The populated <code>PasswordResetRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordResetRequest();

            
            
            

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mobile_number')) {
                obj['mobile_number'] = ApiClient.convertToType(data['mobile_number'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
    * The user's email address
    * @member {String} email
    */
    email = undefined;
    /**
    * The user's mobile phone number
    * @member {String} mobile_number
    */
    mobile_number = undefined;
    /**
    * The user's username
    * @member {String} username
    */
    username = undefined;








}


