/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PaymentMethodTypeResource model module.
* @module model/PaymentMethodTypeResource
* @version 3.0.7
*/
export default class PaymentMethodTypeResource {
    /**
    * Constructs a new <code>PaymentMethodTypeResource</code>.
    * @alias module:model/PaymentMethodTypeResource
    * @class
    * @param id {Number} The id of the payment method type
    * @param name {String} The name of the payment method type
    */

    constructor(id, name) {
        

        
        

        this['id'] = id;this['name'] = name;

        
    }

    /**
    * Constructs a <code>PaymentMethodTypeResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentMethodTypeResource} obj Optional instance to populate.
    * @return {module:model/PaymentMethodTypeResource} The populated <code>PaymentMethodTypeResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentMethodTypeResource();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * The id of the payment method type
    * @member {Number} id
    */
    id = undefined;
    /**
    * The name of the payment method type
    * @member {String} name
    */
    name = undefined;








}


