/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The QuickBuyRequest model module.
* @module model/QuickBuyRequest
* @version 3.0.7
*/
export default class QuickBuyRequest {
    /**
    * Constructs a new <code>QuickBuyRequest</code>.
    * @alias module:model/QuickBuyRequest
    * @class
    * @param sku {String} SKU of item being purchased
    */

    constructor(sku) {
        

        
        

        this['sku'] = sku;

        
    }

    /**
    * Constructs a <code>QuickBuyRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/QuickBuyRequest} obj Optional instance to populate.
    * @return {module:model/QuickBuyRequest} The populated <code>QuickBuyRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuickBuyRequest();

            
            
            

            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * SKU of item being purchased
    * @member {String} sku
    */
    sku = undefined;
    /**
    * ID of the user making the purchase. If null, currently logged in user will be used.
    * @member {Number} user_id
    */
    user_id = undefined;








}


