/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The RevenueCountryReportResource model module.
* @module model/RevenueCountryReportResource
* @version 3.0.7
*/
export default class RevenueCountryReportResource {
    /**
    * Constructs a new <code>RevenueCountryReportResource</code>.
    * @alias module:model/RevenueCountryReportResource
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>RevenueCountryReportResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RevenueCountryReportResource} obj Optional instance to populate.
    * @return {module:model/RevenueCountryReportResource} The populated <code>RevenueCountryReportResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RevenueCountryReportResource();

            
            
            

            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('revenue')) {
                obj['revenue'] = ApiClient.convertToType(data['revenue'], 'Number');
            }
            if (data.hasOwnProperty('volume')) {
                obj['volume'] = ApiClient.convertToType(data['volume'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} country
    */
    country = undefined;
    /**
    * @member {Number} revenue
    */
    revenue = undefined;
    /**
    * @member {Number} volume
    */
    volume = undefined;








}


