/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import KeyValuePairstringstring from './KeyValuePairstringstring';





/**
* The TemplateEmailResource model module.
* @module model/TemplateEmailResource
* @version 3.0.7
*/
export default class TemplateEmailResource {
    /**
    * Constructs a new <code>TemplateEmailResource</code>.
    * @alias module:model/TemplateEmailResource
    * @class
    * @param recipients {Array.<Number>} A list of user ids to send the message to.
    * @param templateKey {String} The key for the template
    */

    constructor(recipients, templateKey) {
        

        
        

        this['recipients'] = recipients;this['template_key'] = templateKey;

        
    }

    /**
    * Constructs a <code>TemplateEmailResource</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TemplateEmailResource} obj Optional instance to populate.
    * @return {module:model/TemplateEmailResource} The populated <code>TemplateEmailResource</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TemplateEmailResource();

            
            
            

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = ApiClient.convertToType(data['recipients'], ['Number']);
            }
            if (data.hasOwnProperty('template_key')) {
                obj['template_key'] = ApiClient.convertToType(data['template_key'], 'String');
            }
            if (data.hasOwnProperty('template_vars')) {
                obj['template_vars'] = ApiClient.convertToType(data['template_vars'], [KeyValuePairstringstring]);
            }
        }
        return obj;
    }

    /**
    * Address to attribute the outgoing message to. Optional if the config email.out_address is set.
    * @member {String} from
    */
    from = undefined;
    /**
    * A list of user ids to send the message to.
    * @member {Array.<Number>} recipients
    */
    recipients = undefined;
    /**
    * The key for the template
    * @member {String} template_key
    */
    template_key = undefined;
    /**
    * A list of variables to fill in the template
    * @member {Array.<module:model/KeyValuePairstringstring>} template_vars
    */
    template_vars = undefined;








}


