/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Property from './Property';





/**
* The TextProperty model module.
* @module model/TextProperty
* @version 3.0.7
*/
export default class TextProperty {
    /**
    * Constructs a new <code>TextProperty</code>.
    * @alias module:model/TextProperty
    * @class
    * @extends module:model/Property
    * @param type {String} The type of the property. Used for polymorphic type recognition and thus must match an expected type with additional properties.
    */

    constructor(type) {
        

        Property.call(this, type);
        

        

        
    }

    /**
    * Constructs a <code>TextProperty</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TextProperty} obj Optional instance to populate.
    * @return {module:model/TextProperty} The populated <code>TextProperty</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextProperty();

            

            Property.constructFromObject(data, obj);
            

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * The value
    * @member {String} value
    */
    value = undefined;








}


