/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WalletAlterRequest model module.
* @module model/WalletAlterRequest
* @version 3.0.7
*/
export default class WalletAlterRequest {
    /**
    * Constructs a new <code>WalletAlterRequest</code>.
    * @alias module:model/WalletAlterRequest
    * @class
    * @param delta {Number} The amount of currency to add/remove. positive to add, negative to remove
    * @param reason {String} The admin entered or system generated reason
    */

    constructor(delta, reason) {
        

        
        

        this['delta'] = delta;this['reason'] = reason;

        
    }

    /**
    * Constructs a <code>WalletAlterRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WalletAlterRequest} obj Optional instance to populate.
    * @return {module:model/WalletAlterRequest} The populated <code>WalletAlterRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WalletAlterRequest();

            
            
            

            if (data.hasOwnProperty('delta')) {
                obj['delta'] = ApiClient.convertToType(data['delta'], 'Number');
            }
            if (data.hasOwnProperty('invoice_id')) {
                obj['invoice_id'] = ApiClient.convertToType(data['invoice_id'], 'Number');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * The amount of currency to add/remove. positive to add, negative to remove
    * @member {Number} delta
    */
    delta = undefined;
    /**
    * The id of an invoice to attribute the transaction to
    * @member {Number} invoice_id
    */
    invoice_id = undefined;
    /**
    * The admin entered or system generated reason
    * @member {String} reason
    */
    reason = undefined;
    /**
    * The transaction type to allow for search/etc
    * @member {String} type
    */
    type = undefined;








}


