/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FacebookToken from '../model/FacebookToken';
import Result from '../model/Result';

/**
* SocialFacebook service.
* @module api/SocialFacebookApi
* @version 3.0.7
*/
export default class SocialFacebookApi {

    /**
    * Constructs a new SocialFacebookApi. 
    * @alias module:api/SocialFacebookApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Link facebook account
     * Links the current user account to a facebook account, using the acccess token from facebook. Can also be used to update the access token after it has expired.
     * @param {Object} opts Optional parameters
     * @param {module:model/FacebookToken} opts.facebookToken The token from facebook
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    linkAccountsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['facebookToken'];


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.apiClient.callApi(
        '/social/facebook/users', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Link facebook account
     * Links the current user account to a facebook account, using the acccess token from facebook. Can also be used to update the access token after it has expired.
     * @param {Object} opts Optional parameters
     * @param {module:model/FacebookToken} opts.facebookToken The token from facebook
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    linkAccounts(opts) {
      return this.linkAccountsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
