/**
 * Knetik Platform API Documentation Latest
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnetikPlatformApiDocumentationLatest);
  }
}(this, function(expect, KnetikPlatformApiDocumentationLatest) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserItemLogResource', function() {
    it('should create an instance of UserItemLogResource', function() {
      // uncomment below and update the code to test UserItemLogResource
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be.a(KnetikPlatformApiDocumentationLatest.UserItemLogResource);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

    it('should have the property info (base name: "info")', function() {
      // uncomment below and update the code to test the property info
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

    it('should have the property item (base name: "item")', function() {
      // uncomment below and update the code to test the property item
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

    it('should have the property logDate (base name: "log_date")', function() {
      // uncomment below and update the code to test the property logDate
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

    it('should have the property userInventory (base name: "user_inventory")', function() {
      // uncomment below and update the code to test the property userInventory
      //var instane = new KnetikPlatformApiDocumentationLatest.UserItemLogResource();
      //expect(instance).to.be();
    });

  });

}));
