/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KnetikPlatformApiDocumentationLatest);
  }
}(this, function(expect, KnetikPlatformApiDocumentationLatest) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KnetikPlatformApiDocumentationLatest.AuthClientsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthClientsApi', function() {
    describe('assignClientGrantTypesUsingPUT', function() {
      it('should call assignClientGrantTypesUsingPUT successfully', function(done) {
        //uncomment below and update the code to test assignClientGrantTypesUsingPUT
        //instance.assignClientGrantTypesUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('assignClientRedirectUrisUsingPUT', function() {
      it('should call assignClientRedirectUrisUsingPUT successfully', function(done) {
        //uncomment below and update the code to test assignClientRedirectUrisUsingPUT
        //instance.assignClientRedirectUrisUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createClientUsingPOST', function() {
      it('should call createClientUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createClientUsingPOST
        //instance.createClientUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteClientUsingDELETE', function() {
      it('should call deleteClientUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteClientUsingDELETE
        //instance.deleteClientUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClientUsingGET', function() {
      it('should call getClientUsingGET successfully', function(done) {
        //uncomment below and update the code to test getClientUsingGET
        //instance.getClientUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClientsUsingGET', function() {
      it('should call getClientsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getClientsUsingGET
        //instance.getClientsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAvailableGrantTypesUsingGET', function() {
      it('should call listAvailableGrantTypesUsingGET successfully', function(done) {
        //uncomment below and update the code to test listAvailableGrantTypesUsingGET
        //instance.listAvailableGrantTypesUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateClientUsingPUT', function() {
      it('should call updateClientUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateClientUsingPUT
        //instance.updateClientUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
